version: '3'

services:
  db:
    image: postgres:latest
    container_name: graphql-api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - mydata:/var/lib/postgresql/data

volumes:
  mydata:
